language: ruby
rvm:
- 2.1
- 2.2
- 2.3
- ruby-head
cache: bundler
sudo: false
before_install: gem install bundler -v 1.10.6
before_script:
#- export CODECLIMATE_REPO_TOKEN=
- export CI=true
script:
- bundle exec rspec
branches:
  only:
  - master
notifications:
  email: false
  slack:
    secure: iJVdq7jPe/vHRBDRZhGOBrvUNqXAVWtfP6yBoZ58RaMcboelaNxZm15o4+EhTCwNb3Sz3wM3MXQo9oQngB31UNpleavg0xK315oFBsQQ24M6oMWdCR6PndWH3sJtf5CZvXUZ0hEZDPG2dkDGTfXF2HyhyotHI3FzrvXAjI8R8sJKxGRVAga0uDAfUntsS19SS8Ftwt6ob3VNKl5GKYElZ4U/gZ3n2e+I8dxiTy9YNBaydNLf33lZe3iZHTQbcRDxH5HbLof0FItGPEvoPJSxnqa6OyfbsTajhRUUOU2m2RInJjSHCliHV1F8nzPjotCl6N7OegO2HJ93FepsZ2dOul/Hbxkb0BuxFxYFgGfS0bHDb66V6JiqmLpwBi/QibP1kVEiP4vizLdX5b32fi/p1L7FRDX00qsYsjEdDyBH5WrWF4yTKTpNotwHmb/E4nFfbtme3jawvSJq5Kg1FL07H3pTP6nUgEKKyYq1FQhxHEGgKHMZYmUG+B7kILgQj3ZM0w7M09Hb2NMDuv7PEr7CbOw6x7ulVUu8ZfgpU7+jKUlnSS8xPN7/kso3hnSWA4PRlNt0Ef9ingUstNpb4wJYDiAmYD7NfFLf4K6CikkcgGXJbV/XYwszb8DKV39vIYDgW0VzREerixo4+SQE0v7FFF1ZQQbQ3yZaQ26UnlYm/Ag=
matrix:
  allow_failures:
  - rvm: ruby-head
  - rvm: 2.3
